from django.core.management.base import BaseCommand, CommandError
from soma_pi.models import Station

class Command(BaseCommand):
    help = 'Initializes the database with all SomaFM stations'

    default_stations = [
        {'name': "Groove Salad",
         'description': "A nicely chilled plate of ambient/downtempo beats and grooves.",
         'url': "http://somafm.com/img/groovesalad120.png",
         'image': "",
          },
        {'name': "Lush",
         'description': "Sensuous and mellow vocals, mostly female, with an electronic influence.",
         'url': "",
         'image': "http://somafm.com/img/lush-x120.jpg",
          },
        {'name': "Drone Zone",
         'description': "Served best chilled, safe with most medications. Atmospheric textures with minimal beats.",
         'url': "",
         'image': "http://somafm.com/img/dronezone120.jpg",
          },
        {'name': "Folk Forward",
         'description': "Indie Folk, Alt-folk and the occasional folk classics.",
         'url': "",
         'image': "http://somafm.com/img/folkfwd120.jpg",
          },
        {'name': "BAGeL Radio",
         'description': "What alternative rock radio should sound like.",
         'url': "",
         'image': "http://somafm.com/img/bagel120.png",
          },
        {'name': "Digitalis",
         'description': "Digitally affected analog rock to calm the agitated heart.",
         'url': "",
         'image': "http://somafm.com/img/digitalis120.png",
          },
        {'name': "Indie Pop Rocks!",
         'description': "New and classic favorite indie pop tracks.",
         'url': "",
         'image': "http://somafm.com/img/indychick.jpg",
          },
        {'name': "PopTron",
         'description': "Electropop and indie dance rock with sparkle and pop.",
         'url': "",
         'image': "http://somafm.com/img/poptron120.png",
          },
        {'name': "Sonic Universe",
         'description': "Transcending the world of jazz with eclectic, avant-garde takes on tradition.",
         'url': "",
         'image': "http://somafm.com/img/sonicuniverse120.jpg",
          },
        {'name': "Covers",
         'description': "Just covers. Songs you know by artists you don't. We've got you covered.",
         'url': "",
         'image': "http://somafm.com/img/covers120.jpg",
          },
        {'name': "Underground 80's",
         'description': "Early 80s UK Synthpop and a bit of New Wave.",
         'url': "",
         'image': "http://somafm.com/img/u80s-120.png",
          },
        {'name': "Secret Agent",
         'description': "The soundtrack for your stylish, mysterious, dangerous life. For Spies and PIs too!",
         'url': "",
         'image': "http://somafm.com/img/secretagent120.jpg",
          },
        {'name': "Suburbs of Goa",
         'description': "Desi-influenced Asian world beats and beyond.",
         'url': "",
         'image': "http://somafm.com/img/sog120.jpg",
          },
        {'name': "Beat Blender",
         'description': "A late night blend of deep-house and downtempo chill.",
         'url': "",
         'image': "http://somafm.com/img/blender120.png",
          },
        {'name': "Dub Step Beyond",
         'description': "Dubstep, Dub and Deep Bass. May damage speakers at high volume.",
         'url': "",
         'image': "http://somafm.com/img/dubstep120.png",
          },
        {'name': "Space Station Soma",
         'description': "Tune in, turn on, space out. Spaced-out ambient and mid-tempo electronica.",
         'url': "",
         'image': "http://somafm.com/img/sss.jpg",
          },
        {'name': "Mission Control",
         'description': "Celebrating NASA and Space Explorers everywhere.",
         'url': "",
         'image': "http://somafm.com/img/missioncontrol120.jpg",
          },
        {'name': "Boot Liquor",
         'description': "Americana Roots music for Cowhands, Cowpokes and Cowtippers",
         'url': "",
         'image': "http://somafm.com/img/bootliquor120.jpg",
          },
        {'name': "Illinois Street Lounge",
         'description': "Classic bachelor pad, playful exotica and vintage music of tomorrow.",
         'url': "",
         'image': "http://somafm.com/img/illstreet.jpg",
          },
        {'name': "The Trip",
         'description': "Progressive house / trance. Tip top tunes.",
         'url': "",
         'image': "http://somafm.com/img/thetrip120.jpg",
          },
        {'name': "cliqhop idm",
         'description': "Blips'n'beeps backed mostly w/beats. Intelligent Dance Music.",
         'url': "",
         'image': "http://somafm.com/img/cliqhop120.png",
          },
        {'name': "Doomed",
         'description': "Dark industrial/ambient music for tortured souls",
         'url': "",
         'image': "http://somafm.com/img/doomed120.png",
          },
        {'name': "Black Rock FM",
         'description': "From the Playa to the world, for the 2013 Burning Man festival.",
         'url': "",
         'image': "http://somafm.com/img/1023brc.jpg",
          },
        {'name': "SF 10-33",
         'description': "Ambient music mixed with the sounds of San Francisco public safety radio traffic.",
         'url': "",
         'image': "http://somafm.com/img/sf1033120.png",
          },
        {'name': "South By Soma",
         'description': "Music from bands who will be performing at SXSW, one of the biggest and best music festivals in the world. [explicit]",
         'url': "",
         'image': "http://somafm.com/img/sxfm120.png",
          },
    ]

    def handle(self, *args, **options):
        for station in self.default_stations:
            new_station = Station()
            new_station.name = station['name']
            new_station.description = station['description']
            new_station.url = station['url']
            new_station.image = station['image']
            new_station.position = 0
            new_station.save()
            self.stdout.write('Added "%s"' % new_station.name)
